-- Açores central: schema PostgreSQL/Supabase.
-- IDs inteiros são mantidos para preservar referências durante a migração SQLite.
create table if not exists clients (
  id bigint primary key,
  name text not null default 'Cliente sem nome', phone text not null unique,
  email text, pet_name text, species text, breed text, pet_age text, pet_weight text,
  notes text, created_at timestamptz not null, updated_at timestamptz not null
);
create table if not exists tickets (
  id bigint primary key, client_id bigint references clients(id) on delete set null,
  phone text not null, subject text not null, category text not null default 'geral',
  status text not null default 'novo', priority text not null default 'normal',
  human_required boolean not null default false, assigned_to text, ai_summary text,
  source text not null default 'whatsapp', ai_paused boolean not null default false,
  created_at timestamptz not null, updated_at timestamptz not null
);
create table if not exists messages (
  id bigint primary key, ticket_id bigint not null references tickets(id) on delete cascade,
  direction text not null, author text not null, body text not null, created_at timestamptz not null
);
create table if not exists notifications (
  id bigint primary key, ticket_id bigint references tickets(id) on delete cascade,
  title text not null, body text not null, level text not null default 'info',
  read_at timestamptz, created_at timestamptz not null
);
create table if not exists appointments (
  id bigint primary key, client_id bigint not null references clients(id), service text not null,
  scheduled_at timestamptz not null, professional text not null default '',
  status text not null default 'aguardando', notes text not null default '', created_at timestamptz not null
);
create table if not exists checklist_items (
  ticket_id bigint not null references tickets(id) on delete cascade, item_key text not null,
  checked boolean not null default false, updated_at timestamptz not null,
  primary key (ticket_id, item_key)
);
create table if not exists neonatal_care (
  id bigint primary key, client_id bigint not null unique references clients(id),
  status text not null default 'observacao', notes text not null default '', next_check timestamptz not null default now(), updated_at timestamptz not null
);
create table if not exists clinic_settings (
  id integer primary key, name text not null, unit text not null, phone text not null default '', address text not null default ''
);
create table if not exists auth_users (
  id bigint primary key, email text not null unique, username text unique, password_hash text not null,
  role text not null, client_id bigint references clients(id) on delete set null,
  active boolean not null default true, platform_admin boolean not null default false,
  must_change_password boolean not null default false
);
create table if not exists auth_sessions (
  hash text primary key, user_id bigint not null references auth_users(id) on delete cascade,
  csrf text not null, created_at bigint not null, expires_at bigint not null, seen_at bigint not null
);
create table if not exists auth_bootstrap (id integer primary key, hash text not null, expires_at bigint not null);
create table if not exists security_audit (
  id bigint generated by default as identity primary key, at timestamptz not null,
  user_id bigint references auth_users(id) on delete set null, event text not null, resource text not null
);
create table if not exists auth_legal_versions (
  version text primary key, terms_content text not null, privacy_content text not null, published_at timestamptz not null
);
create table if not exists auth_legal_acceptance (
  user_id bigint not null references auth_users(id) on delete cascade, version text not null references auth_legal_versions(version), accepted_at timestamptz not null,
  primary key (user_id, version)
);
create table if not exists ai_settings (
  id integer primary key, provider text not null default 'rules', openai_model text not null default 'gpt-4.1-mini',
  gemini_model text not null default 'gemini-3.1-flash-lite', grok_model text not null default 'grok-3-mini',
  openai_secret text, gemini_secret text, grok_secret text, knowledge jsonb not null default '[]'::jsonb, instructions text not null default ''
);
create table if not exists operational_alerts (
  code text primary key, message text not null, classification text not null, first_at timestamptz not null,
  last_at timestamptz not null, count integer not null default 0, active boolean not null default true
);
create table if not exists service_health (id integer primary key, checked_at timestamptz);
create table if not exists conversation_memory (
  id bigint generated by default as identity primary key, phone text not null,
  direction text not null check (direction in ('inbound','outbound')), author text not null, body text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_clients_phone on clients(phone);
create index if not exists idx_tickets_status_priority on tickets(status, priority);
create index if not exists idx_tickets_phone on tickets(phone);
create index if not exists idx_messages_ticket_created on messages(ticket_id, created_at);
create index if not exists idx_notifications_read on notifications(read_at, created_at);
create index if not exists idx_appointments_schedule on appointments(scheduled_at);
create index if not exists idx_conversation_memory_phone on conversation_memory(phone, created_at);
